### ISSUE TITLE
Using private proxies

### ISSUE THREAD

**Issue by Alexell** [opsdisk/yagooglesearch#14] opened 2022-09-20 05:25 UTC
Hello.
Please tell me the format for specifying private proxies, i.e. protected by login and password.

**Comment by opsdisk** [comment] 2022-09-21 00:57
Hi @Alexell - since the `requests` library is being used under the hood, per https://requests.readthedocs.io/en/latest/user/advanced/#proxies you should be able to pass the username and password in the same string like: `http://user:password@host`

So when you instantiate the class it'd look like:

```python
client = yagooglesearch.SearchClient(
    "site:github.com",
    proxy="socks5h://user:password@127.0.0.1:9050,http://user:password@host",
)
```

I don't have a test environment set up at this moment to try it out, so let me know if that does or doesn't work.

**Comment by opsdisk** [comment] 2022-09-28 16:09
Hi @ZeylanEmir can you provide logs or screenshots of what you're seeing?  What type of proxy is it?

**Comment by opsdisk** [comment] 2022-09-29 21:21
@Alexell - Can you validate your proxies are configured and working correctly first?  This example is using a simple HTTP proxy with basic auth and works for me.  However, this specific docker container (https://hub.docker.com/r/monokal/tinyproxy) doesn't handle special characters (`!`, `:`, etc.) in the `BASIC_AUTH_USER` or `BASIC_AUTH_PASSWORD` environment variables.  Thus, I'm not sure if special characters would be handled properly in the requests proxies variable.  A complex password with special characters may screw up the authentication.

Start the container

```bash
docker run --rm \
    -p 8888:8888 \
    --env BASIC_AUTH_USER=test \
    --env BASIC_AUTH_PASSWORD=password123 \
    --env TIMEOUT=30 \
    --name='tinyproxy' \
    monokal/tinyproxy:latest ANY
```

Make sure the Python requests library works...the IP address should be the public IP address of the proxy.

```python

import requests

url = "https://icanhazip.com"

proxies = {
    "http": "http://test:password123@127.0.0.1:8888",
    "https": "http://test:password123@127.0.0.1:8888",
}

response = requests.get(url, proxies=proxies)

print(response.text)
```

Using yagooglesearch...not specifying the proxy username / password fails

```python
import yagooglesearch

query = "site:github.com"

client = yagooglesearch.SearchClient(
    query,
    proxy="http://127.0.0.1:8888",
)
client.assign_random_user_agent()

urls = client.search()

ProxyError: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required')))
```

Using the username / password works

```python
import yagooglesearch

query = "site:github.com"

client = yagooglesearch.SearchClient(
    query,
    proxy="http://test:password123@127.0.0.1:8888",
)
client.assign_random_user_agent()

urls = client.search()

len(urls)
```

**Comment by ZeylanEmir** [comment] 2022-10-01 19:25
I use private proxies, but using your instructions above and checking with myself, I got the following error. The error goes out both on regular proxies and on socks5 socks5 proxies with authorization if i use the yagooglesearch, if i use the requests lib, i get the right response (all info in screenshot's), i using the kali linux (debian):

$ python test.py

2022-10-01 15:08:29,325 [MainThread  ] [INFO] Requesting URL: https://www.google.com/
Traceback (most recent call last):
  File "/home/jacket/.local/lib/python3.10/site-packages/socks.py", line 787, in connect
    super(socksocket, self).connect(proxy_addr)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jacket/.local/lib/python3.10/site-packages/urllib3/contrib/socks.py", line 96, in _new_conn
    conn = socks.create_connection(
  File "/home/jacket/.local/lib/python3.10/site-packages/socks.py", line 209, in create_connection
    raise err
  File "/home/jacket/.local/lib/python3.10/site-packages/socks.py", line 199, in create_connection
    sock.connect((remote_host, remote_port))
  File "/home/jacket/.local/lib/python3.10/site-packages/socks.py", line 47, in wrapper
    return function(*args, **kwargs)
  File "/home/jacket/.local/lib/python3.10/site-packages/socks.py", line 800, in connect
    raise ProxyConnectionError(msg, error)
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 51.38.191.30:7497: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jacket/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/jacket/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/jacket/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/jacket/.local/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/jacket/.local/lib/python3.10/site-packages/urllib3/contrib/socks.py", line 121, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f1238c5e920>, 'Connection to www.google.com timed out. (connect timeout=15)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jacket/.local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/jacket/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/jacket/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: SOCKSHTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f1238c5e920>, 'Connection to www.google.com timed out. (connect timeout=15)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jacket/metagoofil/test.py", line 11, in <module>
    urls = client.search()
  File "/home/jacket/.local/lib/python3.10/site-packages/yagooglesearch/__init__.py", line 429, in search
    html = self.get_page(self.url_home)
  File "/home/jacket/.local/lib/python3.10/site-packages/yagooglesearch/__init__.py", line 323, in get_page
    response = requests.get(
  File "/home/jacket/.local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/jacket/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/jacket/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jacket/.local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/jacket/.local/lib/python3.10/site-packages/requests/adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: SOCK
SHTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f1238c5e920>, 'Connection to www.google.com timed out. (connect timeout=15)'))


I also used the docker image command from the instruction:
docker run --rm \
    -p 8888:8888 \
    --env BASIC_AUTH_USER=test \
    --env BASIC_AUTH_PASSWORD=password123 \
    --env TIMEOUT=30 \
    --name='tinyproxy' \
    monokal/tinyproxy:latest ANY
 and it got stuck on the line:
 INFO      Oct 01 18:32:44 [24]: Starting main loop. Accepting connections.

Perhaps I can be wrong about something, since I'm just starting to work in a unix environment of similar systems, so if I'm wrong somewhere, please point it out.

![index3](https://user-images.githubusercontent.com/84992338/193425126-14e598a2-0733-4fdc-aef1-0fa805512fcd.jpeg)
![index2](https://user-images.githubusercontent.com/84992338/193425127-527267d0-9b4b-43f8-9c12-6aef7a1c5fcd.jpeg)
![index1](https://user-images.githubusercontent.com/84992338/193425130-efa02d1b-f8d2-4d47-a38c-efcc823dcce1.jpeg)
![index](https://user-images.githubusercontent.com/84992338/193425132-40824af5-64e5-4d2b-a5a0-5218608514a7.jpeg)

**Comment by opsdisk** [comment] 2022-10-01 19:35
Thanks for that @ZeylanEmir 

The docker command I provided did not include `-it` (why it was getting stuck) so it should have been:

```bash
docker run --rm -it \
    -p 8888:8888 \
    --env BASIC_AUTH_USER=test \
    --env BASIC_AUTH_PASSWORD=password123 \
    --env TIMEOUT=30 \
    --name='tinyproxy' \
    monokal/tinyproxy:latest ANY
```

I'll dig into it some more.

**Comment by Alexell** [comment] 2022-10-02 04:31
@opsdisk for understanding: Emir and I are working together.
And in metagoofil we have replaced the google library with yagooglesearch.

**Comment by Alexell** [comment] 2022-10-02 04:33
For tests, we use free public proxies, as well as paid private proxies. We do not know what software they are running on and we do not have access to them.

**Comment by opsdisk** [comment] 2022-10-02 21:00
> And in metagoofil we have replaced the google library with yagooglesearch.

Is this issue about you trying to utilize yagooglesearch in metagoofil?!  If so, that's a completely different conversation.  My version of metagoofil is baked into Kali (https://gitlab.com/kalilinux/packages/metagoofil), but I'm not sure simply swapping the libraries would work, I've never tested it.

Assuming you are **not** trying to do that....

So you don't have any issues with the free public proxies?  Do they require a username / password?

Is the issue only with the paid private ones?  Do they require a username / password?  For proxy type, are they HTTP, SOCKS, or both?

Your issue may be valid that yagooglesearch has a bug when using credentials for a proxy, it's just really difficult for me to troubleshoot because I think the problem may be with the proxies, provider, your Python environment, or your understanding of the somewhat advanced networking concept that is proxying.  For example, the proxy provider may:

* block traffic to google.com - or Google blocks traffic from those proxy providers because they are usually shady
* maybe they don't allow for remote DNS lookups (socks5h) vs doing the DNS lookup on your own box (socks5). See https://requests.readthedocs.io/en/latest/user/advanced/?highlight=proxy#socks

> Using the scheme socks5 causes the DNS resolution to happen on the client, rather than on the proxy server. This is in line with curl, which uses the scheme to decide whether to do the DNS resolution on the client or proxy. If you want to resolve the domains on the proxy server, use socks5h as the scheme.

* they have some sort of browser detection and recognize your traffic is not from a browser
* a number of other abuse protection implementations

**Comment by Alexell** [comment] 2022-10-03 12:59
@opsdisk initially we have only **one** problem - metagoofil doesn't work properly and Google is constantly blocking requests (error 429). We with @ZeylanEmir have been looking for ways to make metagoofil work fine for 2 months now (in free time).
We decided to try using a proxy in the hope that it would help. But it turned out that metagoofil does not support proxies.

Now we are trying to replace the `google` library with `yagooglesearch`, because `google` does not support proxies.

Since we've touched on this topic, maybe you, as the author, can help us get the metagoofil to work properly? So that all requests are without 429 errors and that you can repeat requests without restrictions?

From your answer, at least I understood that using public or paid proxies for Google might be even worse. But how then to make metagoofil work normally?

**P.S.** For the rest of the questions, @ZeylanEmir will answer you, because for the most part he is engaged in testing.

**Comment by opsdisk** [comment] 2022-10-04 12:54
Thanks for that clarification...makes much more sense now!

1) In general, creating a separate issue here https://github.com/opsdisk/metagoofil/issues about replacing the `google` library with `yagooglesearch` in Metagoofil would be more appropriate.  I can't promise a quick turnaround with it though.

2) For the time being, check out this section on how to utilize proxies using `proxychains4` for the current version of metagoofil: https://github.com/opsdisk/metagoofil#google-is-blocking-me

I'll keep this issue open for a few more days.

**Comment by ZeylanEmir** [comment] 2022-10-04 19:18
> > And in metagoofil we have replaced the google library with yagooglesearch.
> 
> Is this issue about you trying to utilize `yagooglesearch` in metagoofil instead of the `google` (https://pypi.org/project/google/) library?! If so, that's a completely different conversation. My version of metagoofil is baked into Kali (https://gitlab.com/kalilinux/packages/metagoofil), but I'm not sure simply swapping the libraries would work, I've never tested it.
> 
> Assuming you are **not** trying to do that....
> 
> So you don't have any issues with the free public proxies? Do they require a username / password?
> 
> Is the issue only with the paid private ones? Do they require a username / password? For proxy type, are they HTTP, SOCKS, or both?
> 
> Your issue may be valid that yagooglesearch has a bug when using credentials for a proxy, it's just really difficult for me to troubleshoot because I think the problem may be with the proxies, provider, your Python environment, or your understanding of the somewhat advanced networking concept that is proxying. For example, the proxy provider may:
> 
> * block traffic to google.com - or Google blocks traffic from those proxy providers because they are usually shady
> * maybe they don't allow for remote DNS lookups (socks5h) vs doing the DNS lookup on your own box (socks5). See https://requests.readthedocs.io/en/latest/user/advanced/?highlight=proxy#socks
> 
> > Using the scheme socks5 causes the DNS resolution to happen on the client, rather than on the proxy server. This is in line with curl, which uses the scheme to decide whether to do the DNS resolution on the client or proxy. If you want to resolve the domains on the proxy server, use socks5h as the scheme.
> 
> * they have some sort of browser detection and recognize your traffic is not from a browser
> * a number of other abuse protection implementations

In general, these proxies as simple private and free proxies work fine in simple browsers. We tested both regular proxies and private ones when using requests separately from ya google search and metagoofil, but these proxies do not work on them. We use private proxies SPECIALLY configured to work with google queries, and after testing them as well, I get the same error. Specifically, I use only socks5 proxy, but even testing on https, this problem also remains.

> The docker command I provided did not include -it (why it was getting stuck) so it should have been:

I also checked with the -it command, the program got stuck in the same place, I also used a different docker pub (serjs/go-socks5-proxy), however, the same problem occurred with it on port 1080.



For virtual environments, this is my first experience with python in VMWARE, so I'm not so familiar with what differences there may be from python for a regular machine and a virtual machine. socks5 proxy, namely the user:password field, as well as the field with the ip address, I deliberately hid from prying eyes from the screenshots. These are simple socks5 proxies with authorization, I don't have full control over them, they were selected as special for Google requests, they are not used/run through some third-party application and are launched from outside by a DNS server.


regarding the use of proxychains 4, when running with proxychains and specifying the socks5 proxy both with and without authorization with the settings you specified in your instructions, I get the text with the following error. Also below I attach all other screenshots from my tests including stuck in both socks5 docker containers.

Traceback (most recent call last):
File "/home/jacket/.local/lib/python3.10/site-packages/socks.py", line 787, in connect
super(socksocket, self).connect(proxy_addr)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/jacket/.local/lib/python3.10/site-packages/urllib3/contrib/socks.py", line 96, in _new_conn
conn = socks.create_connection(
File "/home/jacket/.local/lib/python3.10/site-packages/socks.py", line 209, in create_connection
raise err
File "/home/jacket/.local/lib/python3.10/site-packages/socks.py", line 199, in create_connection
sock.connect((remote_host, remote_port))
File "/home/jacket/.local/lib/python3.10/site-packages/socks.py", line 47, in wrapper
return function(*args, **kwargs)
File "/home/jacket/.local/lib/python3.10/site-packages/socks.py", line 800, in connect
raise ProxyConnectionError(msg, error)
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 91.243.61.241:41313: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/jacket/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
httplib_response = self._make_request(
File "/home/jacket/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
self._validate_conn(conn)
File "/home/jacket/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
conn.connect()
File "/home/jacket/.local/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
self.sock = conn = self._new_conn()
File "/home/jacket/.local/lib/python3.10/site-packages/urllib3/contrib/socks.py", line 127, in _new_conn
raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f63849260b0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/jacket/.local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
resp = conn.urlopen(
File "/home/jacket/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
retries = retries.increment(
File "/home/jacket/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: SOCKSHTTPSConnectionPool(host='[www.google.com](https://vk.com/away.php?utf=1&to=http%3A%2F%2Fwww.google.com)', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f63849260b0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/jacket/metagoofil/[metagoofil.py](https://vk.com/away.php?utf=1&to=http%3A%2F%2Fmetagoofil.py)", line 363, in <module>
mg.go()
File "/home/jacket/metagoofil/[metagoofil.py](https://vk.com/away.php?utf=1&to=http%3A%2F%2Fmetagoofil.py)", line 170, in go
urls = client.search()
File "/home/jacket/.local/lib/python3.10/site-packages/yagooglesearch/__init__.py", line 429, in search
html = self.get_page(self.url_home)
File "/home/jacket/.local/lib/python3.10/site-packages/yagooglesearch/__init__.py", line 323, in get_page
response = requests.get(
File "/home/jacket/.local/lib/python3.10/site-packages/requests/api.py", line 73, in get
return request("get", url, params=params, **kwargs)
File "/home/jacket/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
return session.request(method=method, url=url, **kwargs)
File "/home/jacket/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
resp = self.send(prep, **send_kwargs)
File "/home/jacket/.local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
r = adapter.send(request, **kwargs)
File
"/home/jacket/.local/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: SOCKSHTTPSConnectionPool(host='[www.google.com](https://vk.com/away.php?utf=1&to=http%3A%2F%2Fwww.google.com)', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f63849260b0>: Failed to establish a new connection: [Errno 111] Connection refused'))

![ozjWpGJKN1PFU6e-z3YKqy5dnEa_YW6TKvKbplWHqJYCp8dHnxV4LjHCQuQn3L1b39vU7npno3Hpa4IuuxOkYmsH](https://user-images.githubusercontent.com/84992338/193906230-cf694f45-bcf5-4187-b0d4-99beb8c9b5b2.jpg)
![nMjyhm-QNH-4umgIx_ExmAvoNTHFKxyb8jVJXELXrL7LDEG6oyvsW-nkxitaxf8IMuMsPtMSpZ8dfa8F95bHEXxn](https://user-images.githubusercontent.com/84992338/193906276-a89ff901-a9e4-4dfe-b980-92b47f37a5d4.jpg)
![lXvPc0L8iA1iNAyPp1yHNcelwzeWhg_zDOnzwpMqPZCOpWO66JSgbl6Cw5E6RNEPmNfrUTQ4g6mNCtMXKql2sMwY](https://user-images.githubusercontent.com/84992338/193906320-8ac7e039-7ba1-4abc-a171-bf68ab05edc3.jpg)
![gGn9yBVPwiYsStCgznc7aWeagqzkxWBkQ5AK-q_lBTpDYYXjbCJAyEOaKje3_PlQrkd9tnEyv3t3Nj700YmDk-Il](https://user-images.githubusercontent.com/84992338/193906356-d3f324e2-d29f-4d0a-8d31-b1b8d3de697e.jpg)
![SQzn8C0tGf1y5FteFqCsZgquitHFvu_EGY7HAQ3-jeYofYkuQeBTdDz-UnBVJbndEchX368HlnzoWr7cEpQSmsNx](https://user-images.githubusercontent.com/84992338/193906403-f12cb4fb-a447-4e32-b397-f12d1077b986.jpg)

P.S
I read about how proxychains works with socks5 proxies and how to enter them exactly as I indicated in the screenshot on stackoverflow and similar forums, but nothing works either. Can you tell me how it would be possible to solve the problem with the use of proxychains 4 in kali linux, provided you work in a virtual environment?

Additionally, according to your comments regarding the use of python in a virtual environment, I will take into account and unsubscribe here, thank you very much.

@opsdisk

**Comment by opsdisk** [comment] 2022-10-09 22:04
@ZeylanEmir - At this point, the issue has turned into a request to help troubleshoot your proxies and proxy setup for use with the metagoofil tool that you have modified/updated with code I have not seen (you could submit it as PR against the metagoofil repo like I mentioned earlier).  From the point of view of this repo, it is no longer relevant to `yagooglesearch` so I'll be closing the issue.  If you do feel it is a bug or issue with `yagooglesearch`, we can re-open it.  In the mean time, here are some additional resources to help you:

* Check out this link to learn about Python virtual environments - they have nothing to do with a virtual machine: https://docs.python.org/3/library/venv.html
* Check out my book to learn more about SSH tunneling and SOCKS proxies: https://github.com/opsdisk/the_cyber_plumbers_handbook

**Comment by 07h** [comment] 2023-08-19 08:19
Hello. I had a similar error with a proxy with authorization. 

It turns out the problem is in line 212 here.

`self.proxy = proxy.lower()`

if the password and login for the proxy becomes invalid

socks5://LoGiN:PasS@proxy.com:1111 -> socks5://login:pass@proxy.com:1111

**Comment by opsdisk** [comment] 2023-08-19 15:41
Thanks for the comment @07h - I appreciate the feedback.  I'll reopen this issue and take another look...maybe a few days until I can get to it though.

**Comment by opsdisk** [comment] 2024-02-17 14:34
Fixed in https://github.com/opsdisk/yagooglesearch/releases/tag/v1.8.1

**Closed by opsdisk** 2024-02-17 14:34 UTC
